return {
  require 'custom.plugins.flutter',
  require 'custom.plugins.dingllm',
  require 'custom.plugins.indent-blankline',
  require 'custom.plugins.xcodebuild',
  require 'custom.plugins.vim-visual-multi',
  require 'custom.plugins.lualine',
  require 'custom.plugins.alpha',
  require 'custom.plugins.snacks',
  require 'custom.plugins.bufferline',
  require 'custom.plugins.noice',
  require 'custom.plugins.esp',
  require 'custom.plugins.nvim-treesitter-textobjects',
  require 'custom.plugins.mini',
}
